language: ruby
rvm:
- 2.2
branches:
  only:
  - master
deploy:
  api_key:
    secure: ob334CN29nq3432MjB35+DG2tJcd8TeDXsNINv1Vo6KiznsNDFua5awI3jaDuZKzQuKDERcyRufhNgPQYkj/3pn/fwyjLPELhcHhuxkCvj+xDb9oh9+XIhbBh9P2P9770NZ5fZUzEiTxgBnrszrOmHS4QugKg8AH/A9Kez+aMY3jEW2fUPo+wA22959t7sSAB6HY6VWtR0GwCjqjb+p7sGQkG7CHl6cxIzu4CF/4IZ7d0dShZQRgjBzF2/enGjyBAPsaS6NKmJq8zVZCxyTUOhBJxNGI3jVhfj5mgmK5QXFAEv530bpP5TujeE7DG4S2MgfG9mD03J93XypIk+Op4AWoH7+jhOoUYAOSG/5b0TTzXMrcfcFDcXLRh0ZuUWDqvLEUiMT1BdfeHVPKm1GdPghtL+ZMdVpuoIMLCWDYPD2VHssh99AIM6v3JjdKYjCzubNi/AbqfmiZDCeQuzcGxQGHdC5YfZzOriN1/tqatzCQzrbKfSbxkXXULXXMMhlXCwua4EEpkEsTalU14vYp0+3hodcOBNQWV1ePq/c0xWuZXhxVgTTPAczPDrLBj/gdCXPSUKOEL0k7LqkurgNJkwRmAgxwE7CO3Iq0FrRI2uCP7e5ZiCZp5FBC+k1hoQKHgjBhYbBlczmBgWu8v0v7S4NVg1rcmef0/BmM7V/20ww=
