language: ruby
rvm:
- 2.2
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: oH04MS3SR6GAzsvw4r7aVhUn3vwdEceYuQnEGYOu/Avk/AilAjIg0iQDhE4zyRp9TjjRu6amA8Sc0WgKIb2qJEb1NdV+3Jb36i5l/sFEA7zJFq9TrNzNgBno6c02L8fw9WGfBSUiI0Ge7jBKAlEC0N7YKXp6szdZQuPVepez7wKTyZMFI4R8Zk0PZRBA8h5LtA1sJLDu+w3SGsT7DPjJCDLjINLeCETz+9QOmnlsO1XAw0S0UAewW6Qd7i5L4ox50XuJ7nYpVHJfZwhcuHA7iRmZJwwWcccYywSJURoVnGsYubjweB6t9bUES26AUXaX4vYbyHOZfF7gV6DOGcxjX9yQ1g1VmMH4pumcq4y4G8Tihzv6oMzDl0WnkO5fdIGpbUOVPaJ37mvXiGHJduXLMyP1++ZMxEju6LFs9X7oZvs4TEKMmj0+ysmbf46k5j0yyoKzEbBBDgY7swQ07anq+AvPrj68mUVbqq4XTSJ8rI0DyG0LzOT+/C6y8rQH+5tvCAj971o6D6m5iM5UF2GlWvtde7O+U6NEDTpAH7PlGrFvqB7dgUbam5g1FedOpLThNA+5NcTZ/iLrgn1FZfvO3Bk5ywke3b4qMmO/A9ePAAegYdhX5zaeYU5ekgQRzKLw9wO1apJRyt5TvhT4u7YxR+qf3I+YfXj+wFQZbzCbPsE=
