language: ruby
rvm:
- 2.2
branches:
  only:
  - develop
deploy:
  provider: heroku
  app: iic3103t2
  api_key:
    secure: HhQ4H+jsCpdN6psUyhLDabCwjbZOUQ/NnGgtRq5ptRnOxcfhvHEYBxKEwazTnbIgql3CS3l2KkKKnaGOF7IEmIrpSwPY21zoFYc68f5T7UsQCmLBmFBNbqo0ywcbQzY7nAKlF3l5nixnFbKAvUpZSDTBDmgYmeCd8OdV3mcDD/MBmWL+ud4y1mykzuCR//qxXWbLPNEZIUYx/ChSmE3mM9ucatC3bKQffOKT51XlcTUDjC36UHnQg/iLNjK/4L2m1oaoLqk32KtG4bMoGrFD8zux0rIPC3JWNd8Km8sE5AABIA9SVLluuuBwWgRAX5sIvQnuLtGGhDWVDSx4xj0GxetHHJtji6zG2IHlkPrUsmRb6gJkd2V2SlcCAVE9js6yAqyivqMOrzCMUDuyrsmrDqh7bGcOF2nSJWxJzQCEO7V+/lBrOpUn4gzSuBmWvi8ztN9UzrYXbTjy9d4Rg709oMadH3dwXcXSEJ0hswYOFTc5iLohyM20fg9/H01wVvJ4EbH222eJQMoQpAwb46mEvoR/JbkXmq9tf3uC0OJzvV9w4M0swZ8k648u+dSmXHJn2CQeMwItn8LTxz1YSNy1hrFB9NzlWc+Tkgo0kljqLJHFfdVaxELrZL3AVH3k7mypfvo4J08BtejW7YSX5e90Sm33nxh70uS7TrC7NhOU7wQ=
  
